In [7]:
import pandas as pd
import os

In [8]:
# Path to the directory containing the CSV files
data_dir = "C:\\Users\\ashri\\OneDrive\\Desktop\\Bootcamp- Assignments\\citibike-challenge\\JC data"

In [9]:
for filename in os.listdir(data_dir):
    if filename.endswith(".csv"):
        # Read the first few rows of the CSV file into a DataFrame
        sample_df = pd.read_csv(os.path.join(data_dir, filename), nrows=5)
        
        print(f"Columns and data types for {filename}:")
        print(sample_df.dtypes)
        print()

Columns and data types for JC-202301-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202302-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202303-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202304-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202305-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202306-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202307-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202308-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202309-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202310-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202311-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

Columns and data types for JC-202312-citibike-tripdata.csv:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [11]:

# List to store cleaned DataFrames
cleaned_dfs = []

# Iterate over each CSV file in the directory
for filename in os.listdir(data_dir):
    if filename.endswith(".csv"):
        # Read the CSV file into a DataFrame
        df = pd.read_csv(os.path.join(data_dir, filename), low_memory= False)
        
        # # Convert columns to appropriate data types
        # df['start_station_id'] = pd.to_numeric(df['start_station_id'], errors='coerce')
        # df['end_station_id'] = pd.to_numeric(df['end_station_id'], errors='coerce')
        
        # Append cleaned DataFrame to the list
        cleaned_dfs.append(df)

# Combine all cleaned DataFrames into a single DataFrame
combined_df = pd.concat(cleaned_dfs)

# Print the first few rows of the combined DataFrame
print(combined_df.head())

            ride_id  rideable_type           started_at             ended_at  \
0  0905B18B365C9D20   classic_bike  2023-01-28 09:18:10  2023-01-28 09:28:52
1  B4F0562B05CB5404  electric_bike  2023-01-23 20:10:12  2023-01-23 20:18:27
2  5ABF032895F5D87E   classic_bike  2023-01-29 15:27:04  2023-01-29 15:32:38
3  E7E1F9C53976D2F9   classic_bike  2023-01-24 18:35:08  2023-01-24 18:42:13
4  323165780CA0734B   classic_bike  2023-01-21 20:44:09  2023-01-21 20:48:08

                         start_station_name start_station_id  \
0  Hoboken Terminal - Hudson St & Hudson Pl            HB101
1  Hoboken Terminal - Hudson St & Hudson Pl            HB101
2  Hoboken Terminal - Hudson St & Hudson Pl            HB101
3  Hoboken Terminal - Hudson St & Hudson Pl            HB101
4                             Hamilton Park            JC009

                             end_station_name end_station_id  start_lat  \
0                               Hamilton Park          JC009  40.735938
1  Southwest Park - Jackson St & Observer Hwy          HB401  40.735938
2                          Marshall St & 2 St          HB408  40.735944
3                               Hamilton Park          JC009  40.735986
4                                Manila & 1st          JC082  40.727596

   start_lng    end_lat    end_lng member_casual
0 -74.030305  40.727596 -74.044247        member
1 -74.030305  40.737551 -74.041664        member
2 -74.030383  40.740802 -74.042521        member
3 -74.030364  40.727596 -74.044247        member
4 -74.044247  40.721651 -74.042884        member

In [12]:
print(len(combined_df))

#Find the missing values in dataframe
missing_values = combined_df.isna().sum()

# Print the count of missing values for each column
print("Missing values per column:")
print(missing_values)

988851
Missing values per column:
ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name      85
start_station_id        85
end_station_name      3319
end_station_id        3319
start_lat                0
start_lng                0
end_lat                954
end_lng                954
member_casual            0
dtype: int64

In [13]:
# Delete all rows with missing values
combined_df_cleaned = combined_df.dropna()

# Print the length of the cleaned DataFrame after dropping missing values
print(len(combined_df_cleaned))

# Print the count of missing values for each column after dropping
missing_values_after_drop = combined_df_cleaned.isna().sum()
print("Missing values per column after dropping:")
print(missing_values_after_drop)

985519
Missing values per column after dropping:
ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [14]:
combined_df_cleaned.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member

In [15]:
# Define the path for the output CSV file
output_csv_path = "C:\\Users\\ashri\\OneDrive\\Desktop\\Bootcamp- Assignments\\citibike-challenge\\combined_data.csv"

# Write the cleaned DataFrame to a CSV file
combined_df_cleaned.to_csv(output_csv_path, index=False)